Removing posts until I can fix an annoying jekyll error
All of a sudden when building the site I'm seeing the following:

    /Users/andrew/Dropbox/code/andrewsardone.github.com/vendor/bundle/ruby/1.9.1/gems/jekyll-0.11.0/lib/jekyll/convertible.rb:81:in `rescue in do_layout': undefined method `name' for <Post:/2011/03/08/quick-thoughts-on-interface-builder>:Jekyll::Post (NoMethodError)

I'm going to remove posts so I can iteratively update the site. This
should be a non-issue since 1) I don't really write any posts, and 2)
nobody reads the posts.